// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVzU3x2LEF7f6BptDxPizl0Gb9XKjPtQ',
    appId: '1:1065234208210:web:ef3b055b82f9f02c51a40b',
    messagingSenderId: '1065234208210',
    projectId: 'cvnext-a666c',
    authDomain: 'cvnext-a666c.firebaseapp.com',
    storageBucket: 'cvnext-a666c.firebasestorage.app',
    measurementId: 'G-E7RFNJFN5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQwVNJ5Hi1kTT-1Nvk_B-hPGKr7ImwPLs',
    appId: '1:1065234208210:android:6eb869b63943967451a40b',
    messagingSenderId: '1065234208210',
    projectId: 'cvnext-a666c',
    storageBucket: 'cvnext-a666c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGg4x-tEc7aYwB4Kll7ANH1I45U69dj0',
    appId: '1:1065234208210:ios:828cff7e0f39a02451a40b',
    messagingSenderId: '1065234208210',
    projectId: 'cvnext-a666c',
    storageBucket: 'cvnext-a666c.firebasestorage.app',
    iosBundleId: 'com.example.yeniCvUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGg4x-tEc7aYwB4Kll7ANH1I45U69dj0',
    appId: '1:1065234208210:ios:828cff7e0f39a02451a40b',
    messagingSenderId: '1065234208210',
    projectId: 'cvnext-a666c',
    storageBucket: 'cvnext-a666c.firebasestorage.app',
    iosBundleId: 'com.example.yeniCvUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVzU3x2LEF7f6BptDxPizl0Gb9XKjPtQ',
    appId: '1:1065234208210:web:995238ca3f9d9f7551a40b',
    messagingSenderId: '1065234208210',
    projectId: 'cvnext-a666c',
    authDomain: 'cvnext-a666c.firebaseapp.com',
    storageBucket: 'cvnext-a666c.firebasestorage.app',
    measurementId: 'G-VPN5QHEXZG',
  );
}
